-- AY2026 school-calendar fix — APPLY file 3 of 8: Terms 1-3 closure corrections
--
-- Read ay2026-calendar-fix-preview.sql FIRST, then run these files IN ORDER,
-- one file per SQL-editor run. Generated by gen-ay2026-calendar-fix.ts —
-- do not hand-edit; regenerate. Each file is its own transaction and is safe
-- to re-run.
--
-- Every one of these is a closure the register or the published calendar names and the database gets wrong. None changes whether a stored mark counts.
--
--   2026-07-05 T3: no_class -> public_holiday  Youth Day

begin;

drop table if exists _calfix_past_days;
create temp table _calfix_past_days (date, term_number, day_type, hbl_overlay, label) as
values
  (date '2026-07-05', 3, 'public_holiday', false, 'Youth Day');

-- Existing rows: correct in place. Scoped to audience='all' — a
-- primary/secondary override is a deliberate per-level statement and is not
-- this fix's to rewrite.
update school_calendar sc
set day_type = c.day_type,
    hbl_overlay = c.hbl_overlay,
    label = c.label
from _calfix_past_days c
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id and t.term_number = c.term_number
where sc.term_id = t.id
  and sc.date = c.date
  and sc.audience = 'all';

-- Dates with no row at all.
insert into school_calendar (term_id, date, day_type, hbl_overlay, label, audience)
select t.id, c.date, c.day_type, c.hbl_overlay, c.label, 'all'
from _calfix_past_days c
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id and t.term_number = c.term_number
on conflict (term_id, audience, date) do nothing;

-- is_holiday is NOT set here: a BEFORE trigger derives it from day_type
-- (migration 019), and writing it by hand would only be overwritten.

commit;
