-- AY2026 school-calendar fix — APPLY file 4 of 8: Terms 1-3 events
--
-- Read ay2026-calendar-fix-preview.sql FIRST, then run these files IN ORDER,
-- one file per SQL-editor run. Generated by gen-ay2026-calendar-fix.ts —
-- do not hand-edit; regenerate. Each file is its own transaction and is safe
-- to re-run.
--
-- Labels only — no attendance effect. Existing rows are left alone; these are the ones with no row at all.
--
-- NOTE ON SCOPE. `audience` is the best the schema can do today: a level-
-- specific event ("Primary Six Fieldtrip") lands as 'primary', and one that
-- spans both bands ("Leadership Camp", P4-S4) lands as 'all'. The true level
-- list is recorded in lib/sis/backfill/calendar/published-ay2026.ts and in the
-- bracketed scope on each line below, ready for the level column.
--
--   2026-07-03..2026-07-03 T3 school_event [whole school]  Youth Day Celebration

begin;

drop table if exists _calfix_events;
create temp table _calfix_events (start_date, end_date, label, category, audience, term_number) as
values
  (date '2026-07-03', date '2026-07-03', 'Youth Day Celebration', 'school_event', 'all', 3);

-- calendar_events has NO unique constraint, so re-running would duplicate.
-- The NOT EXISTS guard is what makes this file safe to run twice.
insert into calendar_events (term_id, start_date, end_date, label, category, audience, tentative)
select t.id, e.start_date, e.end_date, e.label, e.category, e.audience, false
from _calfix_events e
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id and t.term_number = e.term_number
where not exists (
  select 1 from calendar_events x
  where x.term_id = t.id
    and x.start_date = e.start_date
    and x.end_date = e.end_date
    and x.label = e.label
);

commit;
