-- AY2026 school-calendar fix — APPLY file 5 of 8: Event audience corrections
--
-- Read ay2026-calendar-fix-preview.sql FIRST, then run these files IN ORDER,
-- one file per SQL-editor run. Generated by gen-ay2026-calendar-fix.ts —
-- do not hand-edit; regenerate. Each file is its own transaction and is safe
-- to re-run.
--
-- Nothing to do.

select 'no changes' as note;
