-- AY2026 school-calendar fix — APPLY file 6 of 8: Verification (read-only)
--
-- Read ay2026-calendar-fix-preview.sql FIRST, then run these files IN ORDER,
-- one file per SQL-editor run. Generated by gen-ay2026-calendar-fix.ts —
-- do not hand-edit; regenerate. Each file is its own transaction and is safe
-- to re-run.
--
-- Read-only. Run after files 1-5 and check each result against the preview.

-- 1. Every AY2026 closure, by term.
select t.term_number,
       sc.date,
       to_char(sc.date, 'Dy') as dow,
       sc.day_type,
       sc.hbl_overlay,
       sc.audience,
       sc.label
from school_calendar sc
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where sc.day_type <> 'school_day'
order by sc.date;

-- 2. Event count per term and category — Term 4 should no longer be empty.
select t.term_number, ce.category, ce.audience, count(*) as events
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
group by t.term_number, ce.category, ce.audience
order by t.term_number, ce.category, ce.audience;

-- 3. No duplicate events — re-running files 2 and 4 must not add rows.
select term_id, start_date, end_date, label, count(*) as copies
from calendar_events
group by term_id, start_date, end_date, label
having count(*) > 1;

-- 3b. THE TRIGGER'S POSITIVE CASE — run this AFTER file 07.
--     Everything above proves migration 158's trigger stays silent on a row
--     with no scope. That is the easy half: a rule that never fires passes a
--     "nothing changed" check by doing nothing. This proves it DERIVES, and
--     derives the same answer as lib/sis/backfill/calendar/types.ts::
--     audienceFor, which is the other place the rule is written.
--     Expect ZERO rows. Any row here means the two halves disagree.
select ce.start_date,
       ce.label,
       ce.levels,
       ce.audience as stored,
       case
         when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[]
          and ce.levels && array['S1','S2','S3','S4']::text[] then 'all'
         when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[] then 'primary'
         else 'secondary'
       end as expected
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where ce.levels is not null
  and ce.audience <> case
        when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[]
         and ce.levels && array['S1','S2','S3','S4']::text[] then 'all'
        when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[] then 'primary'
        else 'secondary'
      end;

-- 3c. After file 07, 40 events should carry a level scope. A count of 0 means
--     07 did not run, or its (start_date, label) match found nothing — which
--     happens if it was run BEFORE files 02 and 04 inserted the rows.
select count(*) filter (where ce.levels is not null) as scoped,
       count(*) as total
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026';

-- 4. is_holiday still agrees with day_type (the migration 019 trigger).
select date, day_type, is_holiday
from school_calendar sc
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where sc.is_holiday <> (sc.day_type not in ('school_day', 'hbl'));

-- 5. THE ONE THAT MATTERS: no live attendance mark sits on a day that no
--    longer accepts attendance. Reads the append-only ledger correctly, via
--    the latest row per (section_student_id, date).
with latest as (
  select distinct on (ad.section_student_id, ad.date)
         ad.section_student_id, ad.date, ad.status
  from attendance_daily ad
  order by ad.section_student_id, ad.date, ad.recorded_at desc
)
select l.date, sc.day_type, sc.hbl_overlay, count(*) as stranded_marks
from latest l
join school_calendar sc on sc.date = l.date and sc.audience = 'all'
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where l.status is not null
  and sc.day_type in ('public_holiday', 'school_holiday', 'no_class')
  and not (sc.day_type = 'school_holiday' and sc.hbl_overlay)
group by l.date, sc.day_type, sc.hbl_overlay
order by l.date;
