-- AY2026 school-calendar fix — APPLY file 7 of 8: Level scope — REQUIRES MIGRATION 158
--
-- Read ay2026-calendar-fix-preview.sql FIRST, then run these files IN ORDER,
-- one file per SQL-editor run. Generated by gen-ay2026-calendar-fix.ts —
-- do not hand-edit; regenerate. Each file is its own transaction and is safe
-- to re-run.
--
-- ⚠ RUN MIGRATION 158 FIRST. This file writes calendar_events.levels, which
-- does not exist before it. Run it AFTER files 02 and 04, because it matches
-- rows by the label as it reads IN THE DATABASE — for an event that already
-- existed that is the school's own shorthand ("P5 Fieldtrip"), not the
-- published calendar's wording ("Primary Five Fieldtrip").
--
-- This is the answer to the original report: "P6 Fieldtrip" stops being a
-- whole-school event. `audience` is NOT set here — migration 158's trigger
-- derives it from these levels, which is the point of the column.
--
-- Levels spanning both halves of the school (Leadership Camp, P4-S4) still
-- degrade to audience='all' for the old readers, but the real scope is now
-- stored and the level-aware readers can use it.
--
--   2026-02-25..2026-02-27 [S1,S2,S3,S4]  Secondary School Term 1 Exam
--   2026-02-27 [P1]  Primary One Fieldtrip
--   2026-03-02..2026-03-05 [S1,S2,S3,S4]  Secondary School Term 1 Exam
--   2026-03-04..2026-03-05 [P1,P2,P3,P4,P5,P6]  Primary School Term 1 Exam
--   2026-03-12 [P4]  Primary Four Fieldtrip
--   2026-04-17 [P2,P3]  Primary Two and Three Fieldtrip
--   2026-04-24 [P5]  P5 Fieldtrip
--   2026-05-08 [P6]  P6 Fieldtrip
--   2026-05-13..2026-05-15 [S1,S2,S3,S4]  Secondary School Term 2 Exam
--   2026-05-18..2026-05-21 [P1,P2,P3,P4,P5,P6,S1,S2,S3,S4]  Term 2 Exam
--   2026-07-14..2026-07-16 [P4,P5,P6,S1,S2,S3,S4]  Leadership Camp
--   2026-08-19..2026-08-21 [S1,S2,S3,S4]  Secondary School Term 3 Exam
--   2026-08-20 [S4]  Term 3 Exam (Science Paper 1)
--   2026-08-21 [S3,S4]  Term 3 Exam (English Paper 1&2)
--   2026-08-24..2026-08-27 [S1,S2,S3,S4]  Secondary School Term 3 Exam
--   2026-08-24 [S3]  Term 3 Exam (Biology, Math Paper 1)
--   2026-08-24 [S4]  Term 3 Exam (Chemistry, Math Paper 1)
--   2026-08-24 [S1,S2]  Term 3 Exam (Math Paper 1, MT)
--   2026-08-25 [S1,S2]  Term 3 Exam (History, Science)
--   2026-08-25 [S3]  Term 3 Exam (Literature Paper 2, Geography)
--   2026-08-25 [S1,S2]  Term 3 Exam (Math Paper 1, English)
--   2026-08-25 [S4]  Term 3 Exam (Social Studies, Literature Paper 1)
--   2026-08-26..2026-08-27 [P1,P2,P3,P4,P5,P6]  Primary School Term 3 Exam
--   2026-08-26 [S4]  Term 3 Exam (Biology, Math Paper 2)
--   2026-08-26 [S3]  Term 3 Exam (Chemistry, Social Studies)
--   2026-08-26 [S1,S2]  Term 3 Exam (Humanities, Math Paper 2)
--   2026-08-26 [P1,P2,P3,P4,P5,P6]  Term 3 Exam (Math, English)
--   2026-08-26 [S1,S2]  Term 3 Exam (Science, Computing)
--   2026-08-27 [S4]  Term 3 Exam (Geography, Literature Paper 2)
--   2026-08-27 [S1,S2]  Term 3 Exam (Humanities, Math Paper 2)
--   2026-08-27 [S3]  Term 3 Exam (Literature Paper 1, Math Paper 2)
--   2026-08-27 [P1,P2,P3,P4,P5,P6]  Term 3 Exam (Science, MT)
--   2026-09-17..2026-09-18 [S4]  Secondary Four Retreat
--   2026-09-21..2026-09-25 [S4]  Secondary Four Final Exam
--   2026-09-28..2026-09-30 [S4]  Secondary Four Final Exam
--   2026-10-14..2026-10-16 [S1,S2,S3,S4]  Secondary School Term 4 Exam
--   2026-10-19..2026-10-22 [S1,S2,S3,S4]  Secondary School Term 4 Exam
--   2026-10-21..2026-10-22 [P1,P2,P3,P4,P5,P6]  Primary School Term 4 Exam
--   2026-10-30 [P6]  Primary Six Retreat

begin;

drop table if exists _calfix_levels;
create temp table _calfix_levels (start_date, end_date, label, levels) as
values
  (date '2026-02-25', date '2026-02-27', 'Secondary School Term 1 Exam', array['S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-02-27', date '2026-02-27', 'Primary One Fieldtrip', array['P1']::text[]),
  (date '2026-03-02', date '2026-03-05', 'Secondary School Term 1 Exam', array['S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-03-04', date '2026-03-05', 'Primary School Term 1 Exam', array['P1', 'P2', 'P3', 'P4', 'P5', 'P6']::text[]),
  (date '2026-03-12', date '2026-03-12', 'Primary Four Fieldtrip', array['P4']::text[]),
  (date '2026-04-17', date '2026-04-17', 'Primary Two and Three Fieldtrip', array['P2', 'P3']::text[]),
  (date '2026-04-24', date '2026-04-24', 'P5 Fieldtrip', array['P5']::text[]),
  (date '2026-05-08', date '2026-05-08', 'P6 Fieldtrip', array['P6']::text[]),
  (date '2026-05-13', date '2026-05-15', 'Secondary School Term 2 Exam', array['S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-05-18', date '2026-05-21', 'Term 2 Exam', array['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-07-14', date '2026-07-16', 'Leadership Camp', array['P4', 'P5', 'P6', 'S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-08-19', date '2026-08-21', 'Secondary School Term 3 Exam', array['S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-08-20', date '2026-08-20', 'Term 3 Exam (Science Paper 1)', array['S4']::text[]),
  (date '2026-08-21', date '2026-08-21', 'Term 3 Exam (English Paper 1&2)', array['S3', 'S4']::text[]),
  (date '2026-08-24', date '2026-08-27', 'Secondary School Term 3 Exam', array['S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-08-24', date '2026-08-24', 'Term 3 Exam (Biology, Math Paper 1)', array['S3']::text[]),
  (date '2026-08-24', date '2026-08-24', 'Term 3 Exam (Chemistry, Math Paper 1)', array['S4']::text[]),
  (date '2026-08-24', date '2026-08-24', 'Term 3 Exam (Math Paper 1, MT)', array['S1', 'S2']::text[]),
  (date '2026-08-25', date '2026-08-25', 'Term 3 Exam (History, Science)', array['S1', 'S2']::text[]),
  (date '2026-08-25', date '2026-08-25', 'Term 3 Exam (Literature Paper 2, Geography)', array['S3']::text[]),
  (date '2026-08-25', date '2026-08-25', 'Term 3 Exam (Math Paper 1, English)', array['S1', 'S2']::text[]),
  (date '2026-08-25', date '2026-08-25', 'Term 3 Exam (Social Studies, Literature Paper 1)', array['S4']::text[]),
  (date '2026-08-26', date '2026-08-27', 'Primary School Term 3 Exam', array['P1', 'P2', 'P3', 'P4', 'P5', 'P6']::text[]),
  (date '2026-08-26', date '2026-08-26', 'Term 3 Exam (Biology, Math Paper 2)', array['S4']::text[]),
  (date '2026-08-26', date '2026-08-26', 'Term 3 Exam (Chemistry, Social Studies)', array['S3']::text[]),
  (date '2026-08-26', date '2026-08-26', 'Term 3 Exam (Humanities, Math Paper 2)', array['S1', 'S2']::text[]),
  (date '2026-08-26', date '2026-08-26', 'Term 3 Exam (Math, English)', array['P1', 'P2', 'P3', 'P4', 'P5', 'P6']::text[]),
  (date '2026-08-26', date '2026-08-26', 'Term 3 Exam (Science, Computing)', array['S1', 'S2']::text[]),
  (date '2026-08-27', date '2026-08-27', 'Term 3 Exam (Geography, Literature Paper 2)', array['S4']::text[]),
  (date '2026-08-27', date '2026-08-27', 'Term 3 Exam (Humanities, Math Paper 2)', array['S1', 'S2']::text[]),
  (date '2026-08-27', date '2026-08-27', 'Term 3 Exam (Literature Paper 1, Math Paper 2)', array['S3']::text[]),
  (date '2026-08-27', date '2026-08-27', 'Term 3 Exam (Science, MT)', array['P1', 'P2', 'P3', 'P4', 'P5', 'P6']::text[]),
  (date '2026-09-17', date '2026-09-18', 'Secondary Four Retreat', array['S4']::text[]),
  (date '2026-09-21', date '2026-09-25', 'Secondary Four Final Exam', array['S4']::text[]),
  (date '2026-09-28', date '2026-09-30', 'Secondary Four Final Exam', array['S4']::text[]),
  (date '2026-10-14', date '2026-10-16', 'Secondary School Term 4 Exam', array['S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-10-19', date '2026-10-22', 'Secondary School Term 4 Exam', array['S1', 'S2', 'S3', 'S4']::text[]),
  (date '2026-10-21', date '2026-10-22', 'Primary School Term 4 Exam', array['P1', 'P2', 'P3', 'P4', 'P5', 'P6']::text[]),
  (date '2026-10-30', date '2026-10-30', 'Primary Six Retreat', array['P6']::text[]);

update calendar_events ce
set levels = l.levels
from _calfix_levels l
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id
where ce.term_id = t.id
  and ce.label = l.label
  -- Every row the event covers, not only the one that starts on its first day:
  -- a multi-day event may be stored as one row per date.
  and ce.start_date between l.start_date and l.end_date;

commit;
