-- AY2026 school-calendar fix — APPLY file 8 of 8: Remove rows the sources disproved
--
-- Read ay2026-calendar-fix-preview.sql FIRST, then run these files IN ORDER,
-- one file per SQL-editor run. Generated by gen-ay2026-calendar-fix.ts —
-- do not hand-edit; regenerate. Each file is its own transaction and is safe
-- to re-run.
--
-- A register masthead is typed by hand at the start of term and is sometimes
-- copied from last year. Where it disagrees with the grid beside it, the grid
-- is what teachers actually recorded. These rows came from a masthead and the
-- grid disproves them, so they are removed rather than left to mislead.
--
-- Deleting is correct here and NOT a Hard Rule #6 problem: that rule is about
-- grade entries and audit logs. A calendar event is a label, has its own
-- DELETE route, and carries no history anyone can cite.
--
--   2026-05-12 "Vesak Day"
--     12 May 2026 carries 370 live marks — a full teaching day. Vesak 2026 is 31 May (the published calendar's date, a Sunday, with 1 Jun in lieu; both show zero marks). The T2 masthead is holding AY2025's date, when Vesak fell on 12 May.
--   2026-07-05 "Youth Day Celebration"
--     5 Jul 2026 is a SUNDAY and is Youth Day itself — the register tags 6 Jul SH for the day in lieu. A celebration did not happen on it. The published calendar puts the celebration on Friday 3 Jul, which carries 401 marks. The S1-S4 mastheads filed the public holiday under SCHOOL EVENTS, which also made it look secondary-only.

begin;

drop table if exists _calfix_disproved;
create temp table _calfix_disproved (start_date, label) as
values
  (date '2026-07-05', 'Youth Day Celebration');

delete from calendar_events ce
using _calfix_disproved d,
     academic_years ay,
     terms t
where ay.ay_code = 'AY2026'
  and t.academic_year_id = ay.id
  and ce.term_id = t.id
  and ce.start_date = d.start_date
  and ce.label = d.label;

commit;
