-- AY2026 school-calendar fix — PREVIEW (read-only)
--
-- Generated by gen-ay2026-calendar-fix.ts. Run this, read it,
-- THEN run ay2026-calendar-fix-apply/01..06 in order.
--
-- 0 closure change(s), 0 event insert(s), 0 audience correction(s).
--
-- ── CLOSURE CHANGES ─────────────────────────────────────────────
--
-- ── EVENT INSERTS ───────────────────────────────────────────────
--
-- ── AUDIENCE CORRECTIONS ────────────────────────────────────────
--
-- ── DELIBERATELY NOT APPLIED — your call ────────────────────────
--   2026-07-06 day type
--       published: public_holiday "In Lieu of Youth Day"
--       register:  school_holiday "In Lieu of Youth Day" (T3)
--   2026-09-03 register says closed, but the day has attendance marks
--       published: (nothing on this date)
--       register:  school_holiday "Teacher's Day" (T3)
--   2026-07-05 "Youth Day Celebration" appears on different dates in each source
--       published: 2026-07-03..2026-07-03 "Youth Day Celebration"
--       register:  2026-07-05..2026-07-05 "Youth Day Celebration" (T3)
--   2026-07-14 "Leadership Camp" appears on different dates in each source
--       published: 2026-07-08..2026-07-10 "Leadership Camp (UpperPri - Secondary)"
--       register:  2026-07-14..2026-07-16 "Leadership Camp" (T3)
--   day   2026-07-05 — named in a source conflict
--   day   2026-07-06 — named in a source conflict
--   event 2026-07-03..2026-07-03 "Youth Day Celebration" — the school moved this; the register's dates are already stored
--   event 2026-07-08..2026-07-10 "Leadership Camp (UpperPri - Secondary)" — the school moved this; the register's dates are already stored
--   scope 2026-05-20 "Term 2 Exam" — both bands match (P1,P2,P3,P4,P5,P6,S1,S2,S3,S4); leaving audience='all'
--   event 2026-02-16..2026-02-16 "Chinese New Year Celebration" [whole school] — already covered by the stored 2026-02-16..2026-02-16 "CNY Celebration"
--   event 2026-04-13..2026-04-17 "English Week" [whole school] — already covered by the stored 2026-04-14..2026-04-17 "English Week"
--   event 2026-04-24..2026-04-24 "Primary Five Fieldtrip" [P5] — already covered by the stored 2026-04-24..2026-04-24 "P5 Fieldtrip"
--   event 2026-05-08..2026-05-08 "Primary Six Fieldtrip" [P6] — already covered by the stored 2026-05-08..2026-05-08 "P6 Fieldtrip"
--   event 2026-05-18..2026-05-21 "Secondary School Term 2 Exam" [S1,S2,S3,S4] — already covered by the stored 2026-05-20..2026-05-21 "Term 2 Exam"
--   event 2026-05-20..2026-05-21 "Primary School Term 2 Exam" [P1,P2,P3,P4,P5,P6] — already covered by the stored 2026-05-20..2026-05-21 "Term 2 Exam"
--   event 2026-07-13..2026-07-13 "Moving up photoshoot" [whole school] — already covered by the stored 2026-07-13..2026-07-13 "Moving up and Grad Photoshoot"
--   event 2026-07-14..2026-07-16 "Leadership Camp" [P4,P5,P6,S1,S2,S3,S4] — already covered by the stored 2026-07-15..2026-07-15 "Leadership Camp"
--   event 2026-07-20..2026-07-20 "Moving up photoshoot" [whole school] — already covered by the stored 2026-07-20..2026-07-20 "Moving up and Grad Photoshoot"
--   event 2026-07-21..2026-07-21 "Racial Harmony Day Celebration" [whole school] — already covered by the stored 2026-07-21..2026-07-21 "Racial Harmony Celebration"
--   event 2026-07-27..2026-07-27 "Moving up and Graduation photoshoot" [whole school] — already covered by the stored 2026-07-27..2026-07-27 "Moving up and Grad Photoshoot"
--   event 2026-09-03..2026-09-03 "Teachers and ANTS Day Celebration" [whole school] — already covered by the stored 2026-09-03..2026-09-03 "Teachers and ANTS Day"
--   uncategorised 2026-02-25 [T1] Secondary T1 Exams
--   uncategorised 2026-03-04 [T1] Primary T1 Exam
--   uncategorised 2026-05-12 [T2] Vesak Day

-- Current state, for comparison against the lists above.
select t.term_number,
       sc.date,
       to_char(sc.date, 'Dy') as dow,
       sc.day_type,
       sc.hbl_overlay,
       sc.label
from school_calendar sc
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where sc.day_type <> 'school_day'
  and sc.audience = 'all'
order by sc.date;

select t.term_number, ce.start_date, ce.end_date, ce.category, ce.audience, ce.label
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
order by ce.start_date;
