// scripts/backfill/gen-ay2026-calendar-fix.ts
//
// Generates the preview + apply SQL that brings AY2026's school calendar into
// line with HFSE's two real sources. GENERATES ONLY — writes nothing to the
// database. Read ay2026-calendar-vs-sources-report.txt first.
//
// Run:
//   npx tsx --env-file=.env.local scripts/backfill/gen-ay2026-calendar-fix.ts
//   npx tsx scripts/backfill/lint-generated-sql.ts scripts/backfill/ay2026-calendar-fix-apply
//
// WHAT IT DELIBERATELY LEAVES OUT. A generator that quietly applies a
// judgement call is worse than one that refuses:
//   • the 4 source conflicts — where the published calendar and a register
//     disagree about a date, including the two events the school MOVED
//     (Leadership Camp, Youth Day Celebration). The register's version is
//     already stored; inserting the planned dates as well would put an event
//     in the calendar that never happened.
//   • the 3 register entries no source can categorise (Vesak Day 12 May and
//     two exam shorthands).
//   • everything outside a term window — both calendar tables are term-scoped,
//     so New Year's Day, the term breaks and the Nov-Dec yearend block have
//     nowhere to go.
//   • label rewrites on events that already exist. "Racial Harmony
//     Celebration" versus "Racial Harmony Day Celebration" is churn, not a
//     fix, and rewriting history on a finished term helps nobody.
//
// SAFETY PROPERTY THIS SCRIPT ENFORCES. No date whose day becomes
// NON-encodable may already hold live attendance marks. Otherwise the marks
// would be stranded: recompute_attendance_rollup never joins school_calendar,
// so they keep inflating that child's school_days rather than falling out.
// Clearing marks is a separate, deliberate operation (migration 134) and this
// generator refuses to emit rather than silently require one.
import { mkdirSync, writeFileSync } from 'node:fs';

import { PUBLISHED_AY2026 } from '../../lib/sis/backfill/calendar/published-ay2026';
import { reconcile } from '../../lib/sis/backfill/calendar/reconcile';
import { extractRegisterCalendar } from '../../lib/sis/backfill/calendar/register-legend';
import {
  audienceFor,
  datesCovered,
} from '../../lib/sis/backfill/calendar/types';
import { fetchAllPages } from '../../lib/supabase/paginate';
import { createServiceClient } from '../../lib/supabase/service';

const AY = 'AY2026';
const OUT_DIR = 'scripts/backfill/ay2026-calendar-fix-apply';
const PREVIEW = 'scripts/backfill/ay2026-calendar-fix-preview.sql';

const REGISTERS = [
  {
    file: 'AY2026/T1/T1 Attendance Jan-Mar (1).xlsx',
    termLabel: 'T1',
    year: 2026,
    taught: true,
  },
  {
    file: 'AY2026/T2/T2 Attendance Mar-May (1).xlsx',
    termLabel: 'T2',
    year: 2026,
    taught: true,
  },
  {
    file: 'AY2026/T3/AY2026 Term 3 Attendance (1).xlsx',
    termLabel: 'T3',
    year: 2026,
    taught: true,
  },
];

/** Non-encodable day types — the attendance grid refuses writes (KD #50). */
const NON_ENCODABLE = new Set(['public_holiday', 'school_holiday', 'no_class']);

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const HEADER = (title: string, n: number, of: number) =>
  `-- AY2026 school-calendar fix — APPLY file ${n} of ${of}: ${title}
--
-- Read ay2026-calendar-fix-preview.sql FIRST, then run these files IN ORDER,
-- one file per SQL-editor run. Generated by gen-ay2026-calendar-fix.ts —
-- do not hand-edit; regenerate. Each file is its own transaction and is safe
-- to re-run.
`;

async function main() {
  // ── Sources + intended state ─────────────────────────────────────────────
  const registers = REGISTERS.map((r) => ({
    termLabel: r.termLabel,
    taught: r.taught,
    entries: extractRegisterCalendar(r.file, r.year),
  }));

  const db = createServiceClient();
  const { data: ays } = await db.from('academic_years').select('id, ay_code');
  const ay = (ays ?? []).find((a) => a.ay_code === AY);
  if (!ay) throw new Error(`${AY} not found`);

  const { data: termRows } = await db
    .from('terms')
    .select('id, term_number, start_date, end_date')
    .eq('academic_year_id', ay.id)
    .order('term_number');
  const terms = (termRows ?? []).filter((t) => t.start_date && t.end_date) as {
    id: string;
    term_number: number;
    start_date: string;
    end_date: string;
  }[];
  const termFor = (date: string) =>
    terms.find((t) => date >= t.start_date && date <= t.end_date) ?? null;

  // Live marks, folded to the latest row per (student, date) — attendance_daily
  // is an append-only ledger, so a cleared mark is a newer superseding row.
  const candidateDates = new Set<string>();
  for (const e of PUBLISHED_AY2026)
    for (const d of datesCovered(e)) candidateDates.add(d);
  for (const r of registers)
    for (const e of r.entries)
      for (const d of datesCovered(e)) candidateDates.add(d);
  const ledger = await fetchAllPages<{
    date: string;
    section_student_id: string;
    status: string | null;
  }>((from, to) =>
    db
      .from('attendance_daily')
      .select('date, section_student_id, status, recorded_at')
      .in('date', [...candidateDates].sort())
      .order('recorded_at', { ascending: true })
      .range(from, to)
  );
  const latest = new Map<string, { date: string; status: string | null }>();
  for (const row of ledger) {
    latest.set(`${row.section_student_id}|${row.date}`, {
      date: row.date,
      status: row.status,
    });
  }
  const liveMarks = new Map<string, number>();
  for (const { date, status } of latest.values()) {
    if (status === null) continue;
    liveMarks.set(date, (liveMarks.get(date) ?? 0) + 1);
  }

  const intended = reconcile({
    published: PUBLISHED_AY2026,
    registers,
    datesWithMarks: new Set(liveMarks.keys()),
  });

  // ── Current state ────────────────────────────────────────────────────────
  const termIds = terms.map((t) => t.id);
  const { data: dayRows } = await db
    .from('school_calendar')
    .select('term_id, date, day_type, label, audience, hbl_overlay')
    .in('term_id', termIds);
  const storedDay = new Map(
    (dayRows ?? [])
      .filter((r) => r.audience === 'all')
      .map((r) => [r.date as string, r])
  );
  const { data: eventRows } = await db
    .from('calendar_events')
    .select('term_id, start_date, end_date, label, category, audience')
    .in('term_id', termIds);
  const storedEvents = (eventRows ?? []) as {
    term_id: string;
    start_date: string;
    end_date: string;
    label: string;
    category: string;
    audience: string;
  }[];

  // ── Exclusions ───────────────────────────────────────────────────────────
  // A date named in a conflict is a human's call, not a generator's.
  const conflictDates = new Set(intended.conflicts.map((c) => c.date));
  // For a MOVED event the conflict carries the register's date; the published
  // version sits on different dates and must be excluded by identity.
  const movedPublished = new Set<string>();
  for (const c of intended.conflicts) {
    const m = c.published.match(
      /^(\d{4}-\d{2}-\d{2})\.\.(\d{4}-\d{2}-\d{2}) "(.*)"$/
    );
    if (m) movedPublished.add(`${m[1]}|${m[2]}|${m[3]}`);
  }

  // ── Day changes ──────────────────────────────────────────────────────────
  type DayChange = {
    date: string;
    termNumber: number;
    dayType: string;
    hblOverlay: boolean;
    label: string;
    was: string;
    exists: boolean;
  };
  const dayChanges: DayChange[] = [];
  const skippedDays: string[] = [];

  for (const day of intended.days) {
    const term = termFor(day.date);
    if (!term) continue; // outside every term window — nowhere to store it
    if (conflictDates.has(day.date)) {
      skippedDays.push(`${day.date} — named in a source conflict`);
      continue;
    }
    const stored = storedDay.get(day.date);
    const want = `${day.dayType}${day.hblOverlay ? '+hbl' : ''}`;
    const was = stored
      ? `${stored.day_type}${stored.hbl_overlay ? '+hbl' : ''}`
      : '(no row)';
    if (was === want) continue;

    // THE SAFETY GATE. Only bites when the day stops accepting attendance.
    const becomesNonEncodable =
      NON_ENCODABLE.has(day.dayType) && !day.hblOverlay;
    const marks = liveMarks.get(day.date) ?? 0;
    if (becomesNonEncodable && marks > 0) {
      throw new Error(
        `REFUSING TO EMIT: ${day.date} would become ${want} but holds ${marks} live attendance mark(s). ` +
          `Clearing them is a separate, deliberate step (migration 134) followed by a rollup recompute. ` +
          `Decide that first, then re-run this generator.`
      );
    }

    dayChanges.push({
      date: day.date,
      termNumber: term.term_number,
      dayType: day.dayType,
      hblOverlay: day.hblOverlay,
      label: day.label,
      was,
      exists: Boolean(stored),
    });
  }

  // ── Event inserts ────────────────────────────────────────────────────────
  const sameish = (a: string, b: string) => {
    const n = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '');
    return n(a) === n(b) || n(a).includes(n(b)) || n(b).includes(n(a));
  };

  /**
   * Is this stored row the same happening as this intended event?
   *
   * Two ways to be the same, mirroring reconcile.ts:
   *   1. overlapping dates and recognisably the same name;
   *   2. EXACTLY the same dates and the same category — because the school
   *      does not run two school events of one category on one day.
   *
   * Rule 2 is what stops the original complaint being doubled. The database
   * holds "P5 Fieldtrip" on 24 Apr; the published calendar calls it "Primary
   * Five Fieldtrip". No string compare bridges a numeral and a spelled-out
   * word, so on wording alone this looks like a new event and gets inserted
   * beside the old one — leaving two fieldtrips on one day, which is worse
   * than the mis-scoping we set out to fix.
   *
   * Exams are excluded from rule 2, and only from rule 2: several genuinely
   * different papers share a date, which is exactly the per-level detail the
   * registers exist to preserve.
   */
  const matchesStored = (
    ev: { startDate: string; endDate: string; label: string; category: string },
    s: (typeof storedEvents)[number]
  ) => {
    if (
      s.start_date <= ev.endDate &&
      s.end_date >= ev.startDate &&
      sameish(s.label, ev.label)
    ) {
      return true;
    }
    return (
      ev.category !== 'term_exam' &&
      s.category === ev.category &&
      s.start_date === ev.startDate &&
      s.end_date === ev.endDate
    );
  };
  type EventInsert = {
    startDate: string;
    endDate: string;
    label: string;
    category: string;
    audience: string;
    levels: string;
    termNumber: number;
  };
  const eventInserts: EventInsert[] = [];
  const skippedEvents: string[] = [];
  const fuzzySuppressed: string[] = [];

  for (const ev of intended.events) {
    const term = termFor(ev.startDate);
    if (!term) continue;
    const identity = `${ev.startDate}|${ev.endDate}|${ev.label}`;
    if (movedPublished.has(identity)) {
      skippedEvents.push(
        `${ev.startDate}..${ev.endDate} "${ev.label}" — the school moved this; the register's dates are already stored`
      );
      continue;
    }
    const already = storedEvents.find((s) => matchesStored(ev, s));
    if (already) {
      // A row that matches only APPROXIMATELY is not the same row. Suppressing
      // the insert is the safe choice — a duplicate is worse than a coarse
      // label — but it is not a silent one: the stored row may be broader than
      // what the calendar names (one "Term 2 Exam" standing in for separate
      // primary and secondary sittings), so it is listed for review.
      const exact =
        already.start_date === ev.startDate &&
        already.end_date === ev.endDate &&
        already.label === ev.label;
      if (!exact) {
        fuzzySuppressed.push(
          `${ev.startDate}..${ev.endDate} "${ev.label}" [${ev.levels ? ev.levels.join(',') : 'whole school'}] — already covered by the stored ${already.start_date}..${already.end_date} "${already.label}"`
        );
      }
      continue;
    }
    eventInserts.push({
      startDate: ev.startDate,
      endDate: ev.endDate,
      label: ev.label,
      category: ev.category,
      audience: audienceFor(ev.levels),
      levels: ev.levels ? ev.levels.join(',') : 'whole school',
      termNumber: term.term_number,
    });
  }

  // ── Audience corrections on events that already exist ────────────────────
  // This is the half of Mr Ace's original report the current schema CAN fix:
  // "P6 Fieldtrip" stored as whole-school becomes 'primary'. The level itself
  // still cannot be stored — that is the follow-up.
  type AudienceFix = {
    startDate: string;
    label: string;
    from: string;
    to: string;
    levels: string;
  };
  // Collected per STORED ROW, because several intended events can match one
  // stored row through the fuzzy label compare — and if they disagree about
  // the band, re-scoping is not merely unsafe, it is wrong.
  //
  // The worked example: the database holds one "Term 2 Exam" on 20 May. The
  // published calendar has Primary sitting 20-21 May and Secondary sitting
  // 18-21 May, and "Primary/Secondary School Term 2 Exam" both fuzzy-match
  // "Term 2 Exam". Both bands really did sit exams that day, so 'all' is the
  // correct answer and narrowing it to 'primary' would hide the exam from
  // every secondary teacher. Emitting both rows would also make the UPDATE
  // non-deterministic.
  const wantByStored = new Map<
    string,
    {
      row: (typeof storedEvents)[number];
      wants: Set<string>;
      levels: Set<string>;
    }
  >();
  for (const ev of intended.events) {
    if (ev.levels === null) continue;
    const want = audienceFor(ev.levels);
    if (want === 'all') continue; // mixed-band scope has no honest audience
    const hit = storedEvents.find((s) => matchesStored(ev, s));
    if (!hit) continue;
    const key = `${hit.start_date}|${hit.label}`;
    const bucket = wantByStored.get(key) ?? {
      row: hit,
      wants: new Set<string>(),
      levels: new Set<string>(),
    };
    bucket.wants.add(want);
    for (const l of ev.levels) bucket.levels.add(l);
    wantByStored.set(key, bucket);
  }

  // ── Level scope, for AFTER migration 158 ─────────────────────────────────
  // Kept in its own file so files 01-04 stay runnable against the CURRENT
  // schema — Term 4 is live and must not wait on a migration. Matched by
  // (start_date, label) as the label will read IN THE DATABASE once 02 and 04
  // have run: for a row we insert that is our own label, for a row that
  // already exists it is theirs ("P5 Fieldtrip", not "Primary Five Fieldtrip").
  type LevelScope = {
    startDate: string;
    endDate: string;
    label: string;
    levels: string[];
  };
  const levelScopes: LevelScope[] = [];
  for (const ev of intended.events) {
    if (ev.levels === null || !termFor(ev.startDate)) continue;
    // A moved event's published version is never inserted (see the exclusions
    // above), so scoping it would target a row that will not exist.
    if (movedPublished.has(`${ev.startDate}|${ev.endDate}|${ev.label}`))
      continue;
    const stored = storedEvents.find((s) => matchesStored(ev, s));
    const label = stored ? stored.label : ev.label;
    // ⚠ MATCH THE WHOLE SPAN, NOT JUST THE FIRST DAY. A multi-day event is not
    // necessarily one row: the original T3 import wrote one row per tagged
    // date, so Leadership Camp is three separate one-day rows (14, 15 and 16
    // Jul) that all read "Leadership Camp". Keying on the stored start_date
    // scoped the 14th and left the other two whole-school — the reported bug
    // surviving on two of its three days, with the count still looking right.
    const startDate = ev.startDate;
    const endDate = ev.endDate;

    // One stored row, one scope. Two intended events can land on the same rows
    // — the 20 May "Term 2 Exam" stands in for both bands — and the second
    // write would silently undo the first, so merge instead. Under one label,
    // overlapping ranges are that same collision.
    const existing = levelScopes.find(
      (l) =>
        l.label === label && l.startDate <= endDate && l.endDate >= startDate
    );
    if (existing) {
      if (startDate < existing.startDate) existing.startDate = startDate;
      if (endDate > existing.endDate) existing.endDate = endDate;
      for (const lv of ev.levels) {
        if (!existing.levels.includes(lv)) existing.levels.push(lv);
      }
      continue;
    }
    levelScopes.push({ startDate, endDate, label, levels: [...ev.levels] });
  }
  for (const l of levelScopes) {
    l.levels.sort();
  }

  const audienceFixes: AudienceFix[] = [];
  const ambiguousAudience: string[] = [];
  for (const { row, wants, levels } of wantByStored.values()) {
    if (wants.size > 1) {
      ambiguousAudience.push(
        `${row.start_date} "${row.label}" — both bands match (${[...levels].sort().join(',')}); leaving audience='${row.audience}'`
      );
      continue;
    }
    const want = [...wants][0];
    if (row.audience === want) continue;
    audienceFixes.push({
      startDate: row.start_date,
      label: row.label,
      from: row.audience,
      to: want,
      levels: [...levels].sort().join(','),
    });
  }

  // ── Emit ─────────────────────────────────────────────────────────────────
  mkdirSync(OUT_DIR, { recursive: true });
  const t4Days = dayChanges.filter((d) => d.termNumber === 4);
  const pastDays = dayChanges.filter((d) => d.termNumber !== 4);
  const t4Events = eventInserts.filter((e) => e.termNumber === 4);
  const pastEvents = eventInserts.filter((e) => e.termNumber !== 4);
  const TOTAL = 7;

  writeFileSync(
    `${OUT_DIR}/01-t4-closures.sql`,
    dayFile(
      HEADER('Term 4 closures (LIVE TERM — run this first)', 1, TOTAL),
      t4Days,
      '_calfix_t4_days',
      'Term 4 is open now and holds no closures at all. Without these, teachers can mark attendance on a public holiday.'
    )
  );
  writeFileSync(
    `${OUT_DIR}/02-t4-events.sql`,
    eventFile(
      HEADER('Term 4 events (LIVE TERM)', 2, TOTAL),
      t4Events,
      'Term 4 holds no events at all — including Secondary Four Final Exam.'
    )
  );
  writeFileSync(
    `${OUT_DIR}/03-past-closures.sql`,
    dayFile(
      HEADER('Terms 1-3 closure corrections', 3, TOTAL),
      pastDays,
      '_calfix_past_days',
      'Every one of these is a closure the register or the published calendar names and the database gets wrong. None changes whether a stored mark counts.'
    )
  );
  writeFileSync(
    `${OUT_DIR}/04-past-events.sql`,
    eventFile(
      HEADER('Terms 1-3 events', 4, TOTAL),
      pastEvents,
      'Labels only — no attendance effect. Existing rows are left alone; these are the ones with no row at all.'
    )
  );
  writeFileSync(
    `${OUT_DIR}/05-event-audience.sql`,
    audienceFile(HEADER('Event audience corrections', 5, TOTAL), audienceFixes)
  );
  writeFileSync(
    `${OUT_DIR}/06-verify.sql`,
    verifyFile(HEADER('Verification (read-only)', 6, TOTAL))
  );
  writeFileSync(
    `${OUT_DIR}/07-level-scope.sql`,
    levelScopeFile(
      HEADER('Level scope — REQUIRES MIGRATION 158', 7, TOTAL),
      levelScopes
    )
  );
  writeFileSync(
    PREVIEW,
    previewFile(
      dayChanges,
      eventInserts,
      audienceFixes,
      [
        ...skippedDays.map((s) => `day   ${s}`),
        ...skippedEvents.map((s) => `event ${s}`),
        ...ambiguousAudience.map((s) => `scope ${s}`),
        ...fuzzySuppressed.map((s) => `event ${s}`),
      ],
      intended
    )
  );

  // ── Console summary ──────────────────────────────────────────────────────
  console.log(`Wrote ${PREVIEW}`);
  console.log(`Wrote ${OUT_DIR}/ (${TOTAL} files)`);
  console.log(
    `\nT4 (live):   ${t4Days.length} closure(s), ${t4Events.length} event(s)`
  );
  console.log(
    `T1-T3:       ${pastDays.length} closure(s), ${pastEvents.length} event(s)`
  );
  console.log(`Audience:    ${audienceFixes.length} event(s) re-scoped`);
  console.log(
    `Levels:      ${levelScopes.length} event(s) get a real level scope (file 07, needs migration 158)`
  );
  console.log(
    `\nSKIPPED for a human to decide: ${skippedDays.length} day(s), ${skippedEvents.length} event(s), ` +
      `${intended.conflicts.length} conflict(s), ${intended.uncategorised.length} uncategorised.`
  );
  for (const s of skippedDays) console.log(`  day   ${s}`);
  for (const s of skippedEvents) console.log(`  event ${s}`);
  for (const s of ambiguousAudience) console.log(`  scope ${s}`);
  for (const s of fuzzySuppressed) console.log(`  event ${s}`);
  console.log(
    '\nNo date in this apply loses a live attendance mark — verified before emitting.'
  );
}

// ── file builders ──────────────────────────────────────────────────────────

function dayFile(
  header: string,
  rows: {
    date: string;
    termNumber: number;
    dayType: string;
    hblOverlay: boolean;
    label: string;
    was: string;
  }[],
  tmp: string,
  why: string
): string {
  if (rows.length === 0) {
    return `${header}--\n-- Nothing to do.\n\nselect 'no changes' as note;\n`;
  }
  const notes = rows
    .map(
      (r) =>
        `--   ${r.date} T${r.termNumber}: ${r.was} -> ${r.dayType}${r.hblOverlay ? '+hbl' : ''}  ${r.label}`
    )
    .join('\n');
  // Every VALUES row ends with its comma BEFORE any comment — a trailing
  // comment after a row swallows the separator (lint-generated-sql.ts).
  const values = rows
    .map(
      (r, i) =>
        `  (date ${q(r.date)}, ${r.termNumber}, ${q(r.dayType)}, ${r.hblOverlay}, ${q(r.label)})${i === rows.length - 1 ? ';' : ','}`
    )
    .join('\n');
  return `${header}--
-- ${why}
--
${notes}

begin;

drop table if exists ${tmp};
create temp table ${tmp} (date, term_number, day_type, hbl_overlay, label) as
values
${values}

-- Existing rows: correct in place. Scoped to audience='all' — a
-- primary/secondary override is a deliberate per-level statement and is not
-- this fix's to rewrite.
update school_calendar sc
set day_type = c.day_type,
    hbl_overlay = c.hbl_overlay,
    label = c.label
from ${tmp} c
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id and t.term_number = c.term_number
where sc.term_id = t.id
  and sc.date = c.date
  and sc.audience = 'all';

-- Dates with no row at all.
insert into school_calendar (term_id, date, day_type, hbl_overlay, label, audience)
select t.id, c.date, c.day_type, c.hbl_overlay, c.label, 'all'
from ${tmp} c
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id and t.term_number = c.term_number
on conflict (term_id, audience, date) do nothing;

-- is_holiday is NOT set here: a BEFORE trigger derives it from day_type
-- (migration 019), and writing it by hand would only be overwritten.

commit;
`;
}

function eventFile(
  header: string,
  rows: {
    startDate: string;
    endDate: string;
    label: string;
    category: string;
    audience: string;
    levels: string;
    termNumber: number;
  }[],
  why: string
): string {
  if (rows.length === 0) {
    return `${header}--\n-- Nothing to do.\n\nselect 'no changes' as note;\n`;
  }
  const notes = rows
    .map(
      (r) =>
        `--   ${r.startDate}..${r.endDate} T${r.termNumber} ${r.category} [${r.levels}]  ${r.label}`
    )
    .join('\n');
  const values = rows
    .map(
      (r, i) =>
        `  (date ${q(r.startDate)}, date ${q(r.endDate)}, ${q(r.label)}, ${q(r.category)}, ${q(r.audience)}, ${r.termNumber})${i === rows.length - 1 ? ';' : ','}`
    )
    .join('\n');
  return `${header}--
-- ${why}
--
-- NOTE ON SCOPE. \`audience\` is the best the schema can do today: a level-
-- specific event ("Primary Six Fieldtrip") lands as 'primary', and one that
-- spans both bands ("Leadership Camp", P4-S4) lands as 'all'. The true level
-- list is recorded in lib/sis/backfill/calendar/published-ay2026.ts and in the
-- bracketed scope on each line below, ready for the level column.
--
${notes}

begin;

drop table if exists _calfix_events;
create temp table _calfix_events (start_date, end_date, label, category, audience, term_number) as
values
${values}

-- calendar_events has NO unique constraint, so re-running would duplicate.
-- The NOT EXISTS guard is what makes this file safe to run twice.
insert into calendar_events (term_id, start_date, end_date, label, category, audience, tentative)
select t.id, e.start_date, e.end_date, e.label, e.category, e.audience, false
from _calfix_events e
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id and t.term_number = e.term_number
where not exists (
  select 1 from calendar_events x
  where x.term_id = t.id
    and x.start_date = e.start_date
    and x.end_date = e.end_date
    and x.label = e.label
);

commit;
`;
}

function audienceFile(
  header: string,
  rows: {
    startDate: string;
    label: string;
    from: string;
    to: string;
    levels: string;
  }[]
): string {
  if (rows.length === 0) {
    return `${header}--\n-- Nothing to do.\n\nselect 'no changes' as note;\n`;
  }
  const notes = rows
    .map(
      (r) =>
        `--   ${r.startDate} ${r.from} -> ${r.to}  (really ${r.levels})  ${r.label}`
    )
    .join('\n');
  const values = rows
    .map(
      (r, i) =>
        `  (date ${q(r.startDate)}, ${q(r.label)}, ${q(r.to)})${i === rows.length - 1 ? ';' : ','}`
    )
    .join('\n');
  return `${header}--
-- Events already in the database that name a level but are stored whole-
-- school. This is the half of the scoping problem the current schema can fix;
-- storing the level itself is the follow-up.
--
${notes}

begin;

drop table if exists _calfix_audience;
create temp table _calfix_audience (start_date, label, audience) as
values
${values}

update calendar_events ce
set audience = a.audience
from _calfix_audience a
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id
where ce.term_id = t.id
  and ce.start_date = a.start_date
  and ce.label = a.label;

commit;
`;
}

function levelScopeFile(
  header: string,
  rows: {
    startDate: string;
    endDate: string;
    label: string;
    levels: string[];
  }[]
): string {
  if (rows.length === 0) {
    return `${header}--\n-- Nothing to do.\n\nselect 'no changes' as note;\n`;
  }
  const notes = rows
    .map(
      (r) =>
        `--   ${r.startDate}${r.endDate !== r.startDate ? `..${r.endDate}` : ''} [${r.levels.join(',')}]  ${r.label}`
    )
    .join('\n');
  const values = rows
    .map(
      (r, i) =>
        `  (date ${q(r.startDate)}, date ${q(r.endDate)}, ${q(r.label)}, array[${r.levels.map(q).join(', ')}]::text[])${i === rows.length - 1 ? ';' : ','}`
    )
    .join('\n');
  return `${header}--
-- ⚠ RUN MIGRATION 158 FIRST. This file writes calendar_events.levels, which
-- does not exist before it. Run it AFTER files 02 and 04, because it matches
-- rows by the label as it reads IN THE DATABASE — for an event that already
-- existed that is the school's own shorthand ("P5 Fieldtrip"), not the
-- published calendar's wording ("Primary Five Fieldtrip").
--
-- This is the answer to the original report: "P6 Fieldtrip" stops being a
-- whole-school event. \`audience\` is NOT set here — migration 158's trigger
-- derives it from these levels, which is the point of the column.
--
-- Levels spanning both halves of the school (Leadership Camp, P4-S4) still
-- degrade to audience='all' for the old readers, but the real scope is now
-- stored and the level-aware readers can use it.
--
${notes}

begin;

drop table if exists _calfix_levels;
create temp table _calfix_levels (start_date, end_date, label, levels) as
values
${values}

update calendar_events ce
set levels = l.levels
from _calfix_levels l
join academic_years ay on ay.ay_code = 'AY2026'
join terms t on t.academic_year_id = ay.id
where ce.term_id = t.id
  and ce.label = l.label
  -- Every row the event covers, not only the one that starts on its first day:
  -- a multi-day event may be stored as one row per date.
  and ce.start_date between l.start_date and l.end_date;

commit;
`;
}

function verifyFile(header: string): string {
  return `${header}--
-- Read-only. Run after files 1-5 and check each result against the preview.

-- 1. Every AY2026 closure, by term.
select t.term_number,
       sc.date,
       to_char(sc.date, 'Dy') as dow,
       sc.day_type,
       sc.hbl_overlay,
       sc.audience,
       sc.label
from school_calendar sc
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where sc.day_type <> 'school_day'
order by sc.date;

-- 2. Event count per term and category — Term 4 should no longer be empty.
select t.term_number, ce.category, ce.audience, count(*) as events
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
group by t.term_number, ce.category, ce.audience
order by t.term_number, ce.category, ce.audience;

-- 3. No duplicate events — re-running files 2 and 4 must not add rows.
select term_id, start_date, end_date, label, count(*) as copies
from calendar_events
group by term_id, start_date, end_date, label
having count(*) > 1;

-- 3b. THE TRIGGER'S POSITIVE CASE — run this AFTER file 07.
--     Everything above proves migration 158's trigger stays silent on a row
--     with no scope. That is the easy half: a rule that never fires passes a
--     "nothing changed" check by doing nothing. This proves it DERIVES, and
--     derives the same answer as lib/sis/backfill/calendar/types.ts::
--     audienceFor, which is the other place the rule is written.
--     Expect ZERO rows. Any row here means the two halves disagree.
select ce.start_date,
       ce.label,
       ce.levels,
       ce.audience as stored,
       case
         when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[]
          and ce.levels && array['S1','S2','S3','S4']::text[] then 'all'
         when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[] then 'primary'
         else 'secondary'
       end as expected
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where ce.levels is not null
  and ce.audience <> case
        when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[]
         and ce.levels && array['S1','S2','S3','S4']::text[] then 'all'
        when ce.levels && array['P1','P2','P3','P4','P5','P6']::text[] then 'primary'
        else 'secondary'
      end;

-- 3c. After file 07, 40 events should carry a level scope. A count of 0 means
--     07 did not run, or its (start_date, label) match found nothing — which
--     happens if it was run BEFORE files 02 and 04 inserted the rows.
select count(*) filter (where ce.levels is not null) as scoped,
       count(*) as total
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026';

-- 4. is_holiday still agrees with day_type (the migration 019 trigger).
select date, day_type, is_holiday
from school_calendar sc
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where sc.is_holiday <> (sc.day_type not in ('school_day', 'hbl'));

-- 5. THE ONE THAT MATTERS: no live attendance mark sits on a day that no
--    longer accepts attendance. Reads the append-only ledger correctly, via
--    the latest row per (section_student_id, date).
with latest as (
  select distinct on (ad.section_student_id, ad.date)
         ad.section_student_id, ad.date, ad.status
  from attendance_daily ad
  order by ad.section_student_id, ad.date, ad.recorded_at desc
)
select l.date, sc.day_type, sc.hbl_overlay, count(*) as stranded_marks
from latest l
join school_calendar sc on sc.date = l.date and sc.audience = 'all'
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where l.status is not null
  and sc.day_type in ('public_holiday', 'school_holiday', 'no_class')
  and not (sc.day_type = 'school_holiday' and sc.hbl_overlay)
group by l.date, sc.day_type, sc.hbl_overlay
order by l.date;
`;
}

function previewFile(
  dayChanges: {
    date: string;
    termNumber: number;
    dayType: string;
    hblOverlay: boolean;
    label: string;
    was: string;
  }[],
  eventInserts: {
    startDate: string;
    endDate: string;
    label: string;
    category: string;
    levels: string;
    termNumber: number;
  }[],
  audienceFixes: {
    startDate: string;
    label: string;
    from: string;
    to: string;
    levels: string;
  }[],
  notApplied: string[],
  intended: ReturnType<typeof reconcile>
): string {
  const lines: string[] = [];
  lines.push('-- AY2026 school-calendar fix — PREVIEW (read-only)');
  lines.push('--');
  lines.push('-- Generated by gen-ay2026-calendar-fix.ts. Run this, read it,');
  lines.push('-- THEN run ay2026-calendar-fix-apply/01..06 in order.');
  lines.push('--');
  lines.push(
    `-- ${dayChanges.length} closure change(s), ${eventInserts.length} event insert(s), ${audienceFixes.length} audience correction(s).`
  );
  lines.push('--');
  lines.push(
    '-- ── CLOSURE CHANGES ─────────────────────────────────────────────'
  );
  for (const d of dayChanges) {
    lines.push(
      `--   T${d.termNumber} ${d.date}: ${d.was} -> ${d.dayType}${d.hblOverlay ? '+hbl' : ''}  ${d.label}`
    );
  }
  lines.push('--');
  lines.push(
    '-- ── EVENT INSERTS ───────────────────────────────────────────────'
  );
  for (const e of eventInserts) {
    lines.push(
      `--   T${e.termNumber} ${e.startDate}..${e.endDate} ${e.category} [${e.levels}]  ${e.label}`
    );
  }
  lines.push('--');
  lines.push(
    '-- ── AUDIENCE CORRECTIONS ────────────────────────────────────────'
  );
  for (const a of audienceFixes) {
    lines.push(
      `--   ${a.startDate} ${a.from} -> ${a.to} (really ${a.levels})  ${a.label}`
    );
  }
  lines.push('--');
  lines.push(
    '-- ── DELIBERATELY NOT APPLIED — your call ────────────────────────'
  );
  for (const c of intended.conflicts) {
    lines.push(`--   ${c.date} ${c.what}`);
    lines.push(`--       published: ${c.published}`);
    lines.push(`--       register:  ${c.register}`);
  }
  for (const s of notApplied) lines.push(`--   ${s}`);
  for (const u of intended.uncategorised) {
    lines.push(`--   uncategorised ${u.date} [${u.termLabel}] ${u.label}`);
  }
  lines.push('');
  lines.push('-- Current state, for comparison against the lists above.');
  lines.push(`select t.term_number,
       sc.date,
       to_char(sc.date, 'Dy') as dow,
       sc.day_type,
       sc.hbl_overlay,
       sc.label
from school_calendar sc
join terms t on t.id = sc.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
where sc.day_type <> 'school_day'
  and sc.audience = 'all'
order by sc.date;`);
  lines.push('');
  lines.push(`select t.term_number, ce.start_date, ce.end_date, ce.category, ce.audience, ce.label
from calendar_events ce
join terms t on t.id = ce.term_id
join academic_years ay on ay.id = t.academic_year_id and ay.ay_code = 'AY2026'
order by ce.start_date;`);
  lines.push('');
  return lines.join('\n');
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
