// scripts/backfill/gen-ay2026-primary-subject-configs.ts
// Populates the AY2026 subject_configs/subject_level_offerings rows for
// Primary-relevant subjects that are still missing one, sourced from
// Structure Defaults (template_subject_configs /
// template_subject_level_offerings). Emits SQL for review — does NOT write
// to the database itself.
//
// Scope: only subjects with NO existing AY2026 subject_configs row. The 8
// subjects Phase 3 (grading import) already wrote — verified against real
// T1 workbook data — are never touched (guarded by both the "still
// missing" filter here and by ON CONFLICT DO NOTHING in apply.sql).
//
// These values are template-sourced, NOT verified against real HFSE data
// (no real Primary T1 raw scores exist to check against, unlike Phase 3's
// 8 Secondary subjects). Written with weights_confirmed=false — the
// system's own existing convention (migration 085) for "a config exists
// but a human hasn't confirmed the numbers" — so the Subject Setup page's
// own "needs attention" flag correctly surfaces them for review later.
//
// Run: npx tsx --env-file=.env.local scripts/backfill/gen-ay2026-primary-subject-configs.ts
import { writeFileSync } from 'node:fs';

import { createServiceClient } from '../../lib/supabase/service';
import { sqlString } from '../../lib/sis/backfill/enrollment/sql-escape';

const AY_CODE = 'AY2026';

async function main() {
  const svc = createServiceClient();

  const { data: ay, error: ayErr } = await svc
    .from('academic_years')
    .select('id')
    .eq('ay_code', AY_CODE)
    .single();
  if (ayErr) throw ayErr;
  const ayId = (ay as any).id;

  const { data: levels, error: levelsErr } = await svc
    .from('levels')
    .select('id, code, level_type');
  if (levelsErr) throw levelsErr;
  const primaryLevelIds = new Set(
    (levels ?? [])
      .filter((l: any) => l.level_type === 'primary')
      .map((l: any) => l.id)
  );

  const { data: templateOfferings, error: toErr } = await svc
    .from('template_subject_level_offerings')
    .select('subject_id, level_id, subjects(code), levels(code)');
  if (toErr) throw toErr;

  // Every subject the template says applies to at least one Primary level.
  const primaryRelevantSubjectIds = new Set(
    (templateOfferings ?? [])
      .filter((o: any) => primaryLevelIds.has(o.level_id))
      .map((o: any) => o.subject_id)
  );

  const { data: existingConfigs, error: ecErr } = await svc
    .from('subject_configs')
    .select('subject_id')
    .eq('academic_year_id', ayId);
  if (ecErr) throw ecErr;
  const alreadyConfigured = new Set(
    (existingConfigs ?? []).map((c: any) => c.subject_id)
  );

  const missingSubjectIds = [...primaryRelevantSubjectIds].filter(
    (id) => !alreadyConfigured.has(id)
  );

  const { data: templateConfigs, error: tcErr } = await svc
    .from('template_subject_configs')
    .select(
      'subject_id, ww_weight, pt_weight, qa_weight, ww_max_slots, pt_max_slots, qa_max, subjects(code)'
    )
    .in(
      'subject_id',
      missingSubjectIds.length
        ? missingSubjectIds
        : ['00000000-0000-0000-0000-000000000000']
    );
  if (tcErr) throw tcErr;

  const missingOfferings = (templateOfferings ?? []).filter((o: any) =>
    missingSubjectIds.includes(o.subject_id)
  );

  const preview: string[] = [];
  preview.push(
    '-- AY2026 Primary subject_configs backfill — PREVIEW (read-only)'
  );
  preview.push('--');
  preview.push(
    '-- Generated by gen-ay2026-primary-subject-configs.ts from Structure Defaults'
  );
  preview.push(
    '-- (template_subject_configs / template_subject_level_offerings).'
  );
  preview.push('--');
  preview.push(
    '-- These weights are TEMPLATE-SOURCED, NOT verified against real HFSE'
  );
  preview.push(
    '-- data (unlike the Phase 3 grading import). Written as weights_confirmed=false'
  );
  preview.push(
    '-- so the Subject Setup page\'s own "needs attention" flag surfaces them.'
  );
  preview.push('--');
  preview.push(`-- Subjects to configure (${(templateConfigs ?? []).length}):`);
  for (const c of templateConfigs ?? []) {
    preview.push(
      `--   ${(c as any).subjects.code}: ww=${(c as any).ww_weight} pt=${(c as any).pt_weight} qa=${(c as any).qa_weight} | ww_slots=${(c as any).ww_max_slots} pt_slots=${(c as any).pt_max_slots} qa_max=${(c as any).qa_max}`
    );
  }
  preview.push('--');
  preview.push(
    `-- subject_level_offerings rows to add (${missingOfferings.length}):`
  );
  for (const o of missingOfferings) {
    preview.push(
      `--   ${(o as any).subjects.code} × ${(o as any).levels.code}`
    );
  }
  preview.push('--');
  const already8 = [...alreadyConfigured];
  preview.push(
    `-- Already configured (untouched by this script — ON CONFLICT DO NOTHING): ${already8.length} subjects`
  );

  const apply: string[] = [];
  apply.push(
    '-- AY2026 Primary subject_configs backfill — APPLY (transactional)'
  );
  apply.push('--');
  apply.push('-- RUN ay2026-primary-subject-configs-preview.sql FIRST.');
  apply.push(
    '-- Generated by gen-ay2026-primary-subject-configs.ts — do not hand-edit; regenerate instead.'
  );
  apply.push('--');
  apply.push('begin;');
  apply.push('');

  apply.push('drop table if exists _ay26pri_configs;');
  apply.push(
    'create temp table _ay26pri_configs (subject_code, ww_weight, pt_weight, qa_weight, ww_max_slots, pt_max_slots, qa_max) as'
  );
  apply.push('values');
  const configRows = (templateConfigs ?? []).map(
    (c: any) =>
      `  (${sqlString(c.subjects.code)}, ${c.ww_weight}, ${c.pt_weight}, ${c.qa_weight}, ${c.ww_max_slots}, ${c.pt_max_slots}, ${c.qa_max})`
  );
  apply.push(
    (configRows.length
      ? configRows.join(',\n')
      : "  ('__NONE__', 0, 0, 0, 0, 0, 0)") + ';'
  );
  apply.push('');
  apply.push(
    'insert into subject_configs (academic_year_id, subject_id, ww_weight, pt_weight, qa_weight, ww_max_slots, pt_max_slots, qa_max, weights_confirmed)'
  );
  apply.push(
    'select ay.id, sub.id, c.ww_weight, c.pt_weight, c.qa_weight, c.ww_max_slots, c.pt_max_slots, c.qa_max, false'
  );
  apply.push('from _ay26pri_configs c');
  apply.push(`join academic_years ay on ay.ay_code = ${sqlString(AY_CODE)}`);
  apply.push(
    "join subjects sub on sub.code = c.subject_code and c.subject_code <> '__NONE__'"
  );
  apply.push('on conflict (academic_year_id, subject_id) do nothing;');
  apply.push('');

  apply.push('drop table if exists _ay26pri_offerings;');
  apply.push(
    'create temp table _ay26pri_offerings (subject_code, level_code) as'
  );
  apply.push('values');
  const offeringRows = missingOfferings.map(
    (o: any) => `  (${sqlString(o.subjects.code)}, ${sqlString(o.levels.code)})`
  );
  apply.push(
    (offeringRows.length
      ? offeringRows.join(',\n')
      : "  ('__NONE__', '__NONE__')") + ';'
  );
  apply.push('');
  apply.push(
    'insert into subject_level_offerings (academic_year_id, subject_id, level_id)'
  );
  apply.push('select ay.id, sub.id, lvl.id');
  apply.push('from _ay26pri_offerings o');
  apply.push(`join academic_years ay on ay.ay_code = ${sqlString(AY_CODE)}`);
  apply.push(
    "join subjects sub on sub.code = o.subject_code and o.subject_code <> '__NONE__'"
  );
  apply.push('join levels lvl on lvl.code = o.level_code');
  apply.push(
    'on conflict (subject_id, level_id, academic_year_id) do nothing;'
  );
  apply.push('');
  apply.push('commit;');
  apply.push('');
  apply.push('-- === post-commit verification ===');
  apply.push(
    `select count(*) as subject_configs_rows from subject_configs sc join academic_years ay on ay.id=sc.academic_year_id where ay.ay_code=${sqlString(AY_CODE)};`
  );
  apply.push(
    `select count(*) as subject_level_offerings_rows from subject_level_offerings slo join academic_years ay on ay.id=slo.academic_year_id where ay.ay_code=${sqlString(AY_CODE)};`
  );

  writeFileSync(
    'scripts/backfill/ay2026-primary-subject-configs-preview.sql',
    preview.join('\n') + '\n'
  );
  writeFileSync(
    'scripts/backfill/ay2026-primary-subject-configs-apply.sql',
    apply.join('\n') + '\n'
  );

  console.log('Subjects to configure:', (templateConfigs ?? []).length);
  console.log('Offerings to add:', missingOfferings.length);
  console.log(
    'Wrote scripts/backfill/ay2026-primary-subject-configs-preview.sql'
  );
  console.log(
    'Wrote scripts/backfill/ay2026-primary-subject-configs-apply.sql'
  );
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
